sudo: false

language: python

install:
    - pip install pep8 flake8 sphinx
    - pip install git+https://github.com/myint/rstcheck.git

script:
    - rstcheck `find . -name "*.rst" -printf "%p "`
    - flake8 ./sourcecode/
    - pep8 ./sourcecode/
    - make html
